server:
  servlet:
    contextPath: /
    encoding:
      enabled: true
      force: true
      charset: UTF-8
  port: 5000
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-secret: ${KAKAO_SECRET}
            client-authentication-method: POST
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-id: ${KAKAO_ID}
            scope: profile_nickname,account_email,profile_image
            client-name: kakao
          google:
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            client-secret: ${GOOGLE_SECRET}
            client-id: ${GOOGLE_ID}
            scope: email,profile
        provider:
          kakao:
            user-name-attribute: id
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
  redis:
    host: ${REDIS_HOST}
    port: 6379
    password: ${REDIS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
#      show_sql: true
#      format_sql: true
#      use_sql_comments: true
#    properties:
#      hibernate:
#        show_sql: true   # System out
#        format_sql: true
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      password: ${DB_PASSWORD}
      username: ${DB_USER}
    url: ${DB_URL}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
  data:
    web:
      pageable:
        one-indexed-parameters: true
#springfox:
#  documentation:
#    swagger:

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

#aws
cloud:
  aws:
    credentials:
      secret-key: ${AWS_SECRET_KEY}
      access-key: ${AWS_ACCESS_KEY}
    s3:
      bucket: ${BUCKET_NAME}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

#jwt
jwt:
  secret: ${JWT_SECRET}