version: '3.3'
services:
  spring_prod:
    build: ./back-end
    container_name: springProd
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - BUCKET_NAME=${BUCKET_NAME}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - KAKAO_SECRET=${KAKAO_SECRET}
      - KAKAO_ID=${KAKAO_ID}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
      - GOOGLE_ID=${GOOGLE_ID}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - KAKAO_REDIRECT_URI=${KAKAO_REDIRECT_URI}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - FLASK_DOMAIN=${FLASK_DOMAIN}
    volumes:
      - AI_DATA:/DATA
    command: java -jar /tonemate/build/libs/tonemate-0.0.1-SNAPSHOT.jar
    networks:
      - tonemate_prod

  flask_prod:
    container_name: flaskProd
    build: ./AI
    environment:
      - FLASK_FEATURES=${FLASK_FEATURES}
      - FLASK_TARGET_EPOCH=${FLASK_TARGET_EPOCH}
      - FLASK_MODEL_VERSION=${FLASK_MODEL_VERSION}
    volumes:
      - AI_DATA:/DATA
    command: python app.py
    networks:
      - tonemate_prod
    
  front_prod:
    container_name: frontProd
    build:
      context: ./front-end/tonemate
      dockerfile: docker/production/Dockerfile
    networks:
      - tonemate_prod
volumes:
  AI_DATA:
    external: true
networks:
  tonemate_prod:
    driver: bridge
    external: true
