import Head from 'next/head';
import Intro from '@/components/about/intro';
// import Link from 'next/link';

import { HeroWrapper, HeroContent, Navbar } from '@/components/Layout';
import { useUser } from '@/features/auth';
import { LoadingFallback } from '@/components/Fallbacks';

export default function LandingPage() {
  const { user, isUserLoading } = useUser({ redirectTo: '/home', redirectIfFound: true });
  if (isUserLoading || user) {
    return <LoadingFallback />;
  }

  const title = [
    '자신에게 어울리는 노래를 찾아보세요',
    '녹음 한번으로 분석을',
    '5000곡 그리고 100명',
  ];
  const content = [
    'ToneMate는 유저의 음색과 비슷한 가수를 찾아줍니다.',
    '한 번만 녹음하세요. ToneMate가 당신의 목소리를 분석해드려요.',
    'ToneMate가 맞춤 서비스를 제공하기 위해 분석한 데이터에요.',
  ];
  return (
    <>
      <Head>
        <title>Tonemate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar user={user} />
        <>
          <Head>
            <title>Tonemate 서비스 소개</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main>
            <Intro index={0} title={title[0]} content={content[0]} />
            <Intro index={1} title={title[1]} content={content[1]} />
            <Intro index={2} title={title[2]} content={content[2]} />
          </main>
        </>
      </main>
    </>
  );
}
