import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import { useRouter } from 'next/router';

import { API_URL } from '@/config';

import loginButton from '@/assets/kakao_login_large_narrow.png';

export default function LoginPage() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="grid h-screen w-screen place-items-center bg-base-200">
          <div className="grid h-96 w-96 place-items-center rounded-md">
            <Link href={`${API_URL}/oauth2/authorization/kakao`}>
              <Image src={loginButton} alt="Kakao login" />
            </Link>
          </div>
        </div>
      </main>
    </>
  );
}
