import Head from 'next/head';
import Layout from '@/components/layout';
import TitleContainer from '@/components/content/title-container';
import MainContainer from '@/components/content/main-container';
// import MyListComponent from '@/components/main/my-list-component';
import TableLike from '@/components/table/table-like';

export default function MusicList() {
  return (
    <>
      <Head>
        <title>애창곡 리스트</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <TitleContainer>
            <p className="text-xl text-white lg:text-4xl">애창곡 리스트</p>
          </TitleContainer>
          <MainContainer>
            {/* <MyListComponent></MyListComponent> */}
            <TableLike />
          </MainContainer>
        </Layout>
      </main>
    </>
  );
}
