import Head from 'next/head';
import dynamic from 'next/dynamic';

import Layout from '@/components/layout';
import TitleContainer from '@/components/content/title-container';
import MainContainer from '@/components/content/main-container';
const RecorderRange = dynamic(
  () => import('@/features/inspectation').then((res) => res.RecorderRange),
  { ssr: false }
);

export default function VocalRange() {
  return (
    <>
      <Head>
        <title>음역대검사</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <TitleContainer>
            <p className="text-xl text-white lg:text-4xl">음역대 검사</p>
          </TitleContainer>
          <MainContainer>
            <RecorderRange />
          </MainContainer>
        </Layout>
      </main>
    </>
  );
}
