import Head from 'next/head';
import dynamic from 'next/dynamic';

import Layout from '@/components/layout';
import TitleContainer from '@/components/content/title-container';
import MainContainer from '@/components/content/main-container';
const RecorderColor = dynamic(
  () => import('@/features/inspectation').then((res) => res.RecorderColor),
  { ssr: false }
);

export default function VocalColor() {
  return (
    <>
      <Head>
        <title>음색검사</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <TitleContainer>
            <p className="text-xl text-white lg:text-4xl">음색검사</p>
          </TitleContainer>
          <MainContainer>
            <RecorderColor />
          </MainContainer>
        </Layout>
      </main>
    </>
  );
}
